name: Vulnerability Detection CI Pipeline

on:
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: "0 12 * * 6"

jobs:
  fs-scan:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
